[LG-73] - try to get version id when the package does not exist

diff --git a/.github/workflows/c-delivery.yaml b/.github/workflows/c-delivery.yaml
--- a/.github/workflows/c-delivery.yaml
+++ b/.github/workflows/c-delivery.yaml
@@ -94,17 +94,27 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           
-          RESPONSE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
+          RESPONSE=$(curl -s -w "%{http_code}" -o response.json \
+            -H "Authorization: Bearer $GITHUB_TOKEN" \
             -H "Accept: application/vnd.github.v3+json" \
             "https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/${{ env.ENCODED_PATH }}/versions")
           
-          if [ -z "RESPONSE" ]; then
-            echo "The RESPONSE  not found."
+          STATUS_CODE="${RESPONSE: -3}"
+          CONTENT=$(cat response.json)
+          
+          if [[ $STATUS_CODE != 2* ]]; then
+            echo "Error: Received status code $STATUS_CODE. Exiting step."
+            echo "Response content: $CONTENT"
+            echo "image_exists=false" >> $GITHUB_OUTPUT
+            exit 1
+          fi
+          if [ -z "$CONTENT" ]; then
+            echo "The RESPONSE not found."
             echo "image_exists=false" >> $GITHUB_OUTPUT
             exit 1
           fi
           
-          VERSION_ID=$(echo "$RESPONSE" | jq -r ".[] | select(.metadata.container.tags[] == \"${{ env.version }}\") | .id")
+          VERSION_ID=$(echo "$CONTENT" | jq -r ".[] | select(.metadata.container.tags[] == \"${{ env.version }}\") | .id")
 
           if [ -z "$VERSION_ID" ]; then
             echo "Error: Version ID for image tag '${{ env.version }}' not found."
